name: Build and Deploy
on:
  push:
  pull_request:
    types: [reopened]

permissions:
  contents: write
  pull-requests: write
  deployments: write

env:
  BRANCH_NAME: ${{ github.head_ref || github.ref_name }}

jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: staging-${{ env.BRANCH_NAME }}

      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Building Storybook
        run: |
          yarn
          STORYBOOK_BUILD_PATH=${{ env.BRANCH_NAME }} yarn run build-storybook

      - name: Create a version mark
        run: |
          touch ./storybook-static/${{ github.sha }}.txt

      - name: Pushing to pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: storybook-pages
          folder: storybook-static
          target-folder: ${{ env.BRANCH_NAME }}

      - name: Wait for GitHub Pages to be deployed
        uses: mydea/action-wait-for-api@v1
        with:
          url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.BRANCH_NAME }}/${{ github.sha }}.txt
          expected-status: 200
          timeout: 600
          interval: 15

      - name: Update deployment status
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          env_url: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/${{ env.BRANCH_NAME }}
